services:
  fea:
    image: flint-eats-server
    build: ./
    environment:
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5432/eats
      - DATABASE_USER=eats
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USER=dkurin@swiftlet.technology
    secrets:
      - DATABASE_PASSWORD
      - MAIL_PASS
    ports:
      - 8080:8080

secrets:
  DATABASE_PASSWORD:
    file: ./.secrets/DATABASE_PASSWORD.txt
  MAIL_PASS:
    file: ./.secrets/MAIL_PASS.txt