services:
  fea-dev:
    image: "dantheman2865/flint-eats-server:${IMAGE_VER}"
    environment:
      - DATABASE_URL=jdbc:postgresql://private-flinteats-do-user-3442489-0.b.db.ondigitalocean.com:25060/flinteats-dev
      - DATABASE_USER=flinteats-dev
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USER=dkurin@swiftlet.technology
      - DO_SPACE_KEY=DO00WXVL2TJJFZ44FPT2
      - DO_SPACE_ENDPOINT=https://nyc3.digitaloceanspaces.com
      - DO_SPACE_REGION=nyc3
      - DO_SPACE_BUCKET=flinteats
      - DO_SPACE_PREFIX=dev/
    restart: always
    secrets:
      - DATABASE_PASSWORD
      - MAIL_PASS
      - DO_SPACE_SECRET
    ports:
      - 8081:8080
  postgrest-dev:
    container_name: postgrest
    image: postgrest/postgrest:v12.2.3
    ports:
      - "3001:3000"
    # Available environment variables documented here:
    # https://postgrest.org/en/latest/configuration.html#environment-variables
    environment:
      # The name of which database schema to expose to REST clients
      - PGRST_DB_SCHEMA=public
      # The database role to use when no client authentication is provided
      - PGRST_DB_ANON_ROLE=web_anon
      # Overrides the base URL used within the OpenAPI self-documentation hosted at the API root path
      - PGRST_OPENAPI_SERVER_PROXY_URI=https://fea.swiftlet.dev/pg
    secrets:
      - PGRST_DB_URI
    restart: always

secrets:
  DATABASE_PASSWORD:
    file: secrets/DEV_DATABASE_PASSWORD.txt
  MAIL_PASS:
    file: secrets/MAIL_PASS.txt
  DO_SPACE_SECRET:
    file: secrets/S3_SECRET.txt
  PGRST_DB_URI:
    environment: secrets/DEV_PGRST_URI.txt
