// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.etshost.msu.entity;

import com.etshost.msu.entity.Badge;
import com.etshost.msu.entity.BadgeDataOnDemand;
import com.etshost.msu.entity.Status;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect BadgeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BadgeDataOnDemand: @Component;
    
    private Random BadgeDataOnDemand.rnd = new SecureRandom();
    
    private List<Badge> BadgeDataOnDemand.data;
    
    public Badge BadgeDataOnDemand.getNewTransientBadge(int index) {
        Badge obj = new Badge();
        setAvatar(obj, index);
        setCreated(obj, index);
        setModified(obj, index);
        setStatus(obj, index);
        return obj;
    }
    
    public void BadgeDataOnDemand.setAvatar(Badge obj, int index) {
        byte[] avatar = String.valueOf(index).getBytes();
        obj.setAvatar(avatar);
    }
    
    public void BadgeDataOnDemand.setCreated(Badge obj, int index) {
        Instant created = null;
        obj.setCreated(created);
    }
    
    public void BadgeDataOnDemand.setModified(Badge obj, int index) {
        Instant modified = null;
        obj.setModified(modified);
    }
    
    public void BadgeDataOnDemand.setStatus(Badge obj, int index) {
        Status status = Status.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    public Badge BadgeDataOnDemand.getSpecificBadge(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Badge obj = data.get(index);
        Long id = obj.getId();
        return Badge.findBadge(id);
    }
    
    public Badge BadgeDataOnDemand.getRandomBadge() {
        init();
        Badge obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Badge.findBadge(id);
    }
    
    public boolean BadgeDataOnDemand.modifyBadge(Badge obj) {
        return false;
    }
    
    public void BadgeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Badge.findBadgeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Badge' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Badge>();
        for (int i = 0; i < 10; i++) {
            Badge obj = getNewTransientBadge(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
