// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.etshost.msu.entity;

import com.etshost.msu.entity.Comment;
import com.etshost.msu.entity.CommentDataOnDemand;
import com.etshost.msu.entity.CommentIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CommentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CommentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CommentIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CommentIntegrationTest: @Transactional;
    
    @Autowired
    CommentDataOnDemand CommentIntegrationTest.dod;
    
    @Test
    public void CommentIntegrationTest.testCountComments() {
        Assert.assertNotNull("Data on demand for 'Comment' failed to initialize correctly", dod.getRandomComment());
        long count = Comment.countComments();
        Assert.assertTrue("Counter for 'Comment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CommentIntegrationTest.testFindComment() {
        Comment obj = dod.getRandomComment();
        Assert.assertNotNull("Data on demand for 'Comment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Comment' failed to provide an identifier", id);
        obj = Comment.findComment(id);
        Assert.assertNotNull("Find method for 'Comment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Comment' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CommentIntegrationTest.testFindAllComments() {
        Assert.assertNotNull("Data on demand for 'Comment' failed to initialize correctly", dod.getRandomComment());
        long count = Comment.countComments();
        Assert.assertTrue("Too expensive to perform a find all test for 'Comment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Comment> result = Comment.findAllComments();
        Assert.assertNotNull("Find all method for 'Comment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Comment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CommentIntegrationTest.testFindCommentEntries() {
        Assert.assertNotNull("Data on demand for 'Comment' failed to initialize correctly", dod.getRandomComment());
        long count = Comment.countComments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Comment> result = Comment.findCommentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Comment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Comment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CommentIntegrationTest.testFlush() {
        Comment obj = dod.getRandomComment();
        Assert.assertNotNull("Data on demand for 'Comment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Comment' failed to provide an identifier", id);
        obj = Comment.findComment(id);
        Assert.assertNotNull("Find method for 'Comment' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyComment(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Comment' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CommentIntegrationTest.testMergeUpdate() {
        Comment obj = dod.getRandomComment();
        Assert.assertNotNull("Data on demand for 'Comment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Comment' failed to provide an identifier", id);
        obj = Comment.findComment(id);
        boolean modified =  dod.modifyComment(obj);
        Integer currentVersion = obj.getVersion();
        Comment merged = (Comment)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Comment' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CommentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Comment' failed to initialize correctly", dod.getRandomComment());
        Comment obj = dod.getNewTransientComment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Comment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Comment' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Comment' identifier to no longer be null", obj.getId());
    }
    
}
