// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.etshost.msu.entity;

import com.etshost.msu.entity.Deal;
import com.etshost.msu.entity.DealDataOnDemand;
import com.etshost.msu.entity.MarketDataOnDemand;
import com.etshost.msu.entity.Status;
import com.etshost.msu.entity.UserDataOnDemand;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DealDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DealDataOnDemand: @Component;
    
    private Random DealDataOnDemand.rnd = new SecureRandom();
    
    private List<Deal> DealDataOnDemand.data;
    
    @Autowired
    MarketDataOnDemand DealDataOnDemand.marketDataOnDemand;
    
    @Autowired
    UserDataOnDemand DealDataOnDemand.userDataOnDemand;
    
    public Deal DealDataOnDemand.getNewTransientDeal(int index) {
        Deal obj = new Deal();
        setCreated(obj, index);
        setEndDate(obj, index);
        setImage(obj, index);
        setModified(obj, index);
        setPrice(obj, index);
        setStartDate(obj, index);
        setStatus(obj, index);
        setText(obj, index);
        setTitle(obj, index);
        return obj;
    }
    
    public void DealDataOnDemand.setCreated(Deal obj, int index) {
        Instant created = null;
        obj.setCreated(created);
    }
    
    public void DealDataOnDemand.setEndDate(Deal obj, int index) {
        Instant endDate = null;
        obj.setEndDate(endDate);
    }
    
    public void DealDataOnDemand.setImage(Deal obj, int index) {
        byte[] image = String.valueOf(index).getBytes();
        obj.setImage(image);
    }
    
    public void DealDataOnDemand.setModified(Deal obj, int index) {
        Instant modified = null;
        obj.setModified(modified);
    }
    
    public void DealDataOnDemand.setPrice(Deal obj, int index) {
        String price = "price_" + index;
        obj.setPrice(price);
    }
    
    public void DealDataOnDemand.setStartDate(Deal obj, int index) {
        Instant startDate = null;
        obj.setStartDate(startDate);
    }
    
    public void DealDataOnDemand.setStatus(Deal obj, int index) {
        Status status = Status.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    public void DealDataOnDemand.setText(Deal obj, int index) {
        String text = "text_" + index;
        obj.setText(text);
    }
    
    public void DealDataOnDemand.setTitle(Deal obj, int index) {
        String title = "title_" + index;
        obj.setTitle(title);
    }
    
    public Deal DealDataOnDemand.getSpecificDeal(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Deal obj = data.get(index);
        Long id = obj.getId();
        return Deal.findDeal(id);
    }
    
    public Deal DealDataOnDemand.getRandomDeal() {
        init();
        Deal obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Deal.findDeal(id);
    }
    
    public boolean DealDataOnDemand.modifyDeal(Deal obj) {
        return false;
    }
    
    public void DealDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Deal.findDealEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Deal' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Deal>();
        for (int i = 0; i < 10; i++) {
            Deal obj = getNewTransientDeal(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
