// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.etshost.msu.entity;

import com.etshost.msu.entity.Food;
import com.etshost.msu.entity.FoodDataOnDemand;
import com.etshost.msu.entity.FoodIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FoodIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FoodIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FoodIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FoodIntegrationTest: @Transactional;
    
    @Autowired
    FoodDataOnDemand FoodIntegrationTest.dod;
    
    @Test
    public void FoodIntegrationTest.testCountFoods() {
        Assert.assertNotNull("Data on demand for 'Food' failed to initialize correctly", dod.getRandomFood());
        long count = Food.countFoods();
        Assert.assertTrue("Counter for 'Food' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FoodIntegrationTest.testFindFood() {
        Food obj = dod.getRandomFood();
        Assert.assertNotNull("Data on demand for 'Food' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Food' failed to provide an identifier", id);
        obj = Food.findFood(id);
        Assert.assertNotNull("Find method for 'Food' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Food' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FoodIntegrationTest.testFindAllFoods() {
        Assert.assertNotNull("Data on demand for 'Food' failed to initialize correctly", dod.getRandomFood());
        long count = Food.countFoods();
        Assert.assertTrue("Too expensive to perform a find all test for 'Food', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Food> result = Food.findAllFoods();
        Assert.assertNotNull("Find all method for 'Food' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Food' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FoodIntegrationTest.testFindFoodEntries() {
        Assert.assertNotNull("Data on demand for 'Food' failed to initialize correctly", dod.getRandomFood());
        long count = Food.countFoods();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Food> result = Food.findFoodEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Food' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Food' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FoodIntegrationTest.testFlush() {
        Food obj = dod.getRandomFood();
        Assert.assertNotNull("Data on demand for 'Food' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Food' failed to provide an identifier", id);
        obj = Food.findFood(id);
        Assert.assertNotNull("Find method for 'Food' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFood(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Food' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FoodIntegrationTest.testMergeUpdate() {
        Food obj = dod.getRandomFood();
        Assert.assertNotNull("Data on demand for 'Food' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Food' failed to provide an identifier", id);
        obj = Food.findFood(id);
        boolean modified =  dod.modifyFood(obj);
        Integer currentVersion = obj.getVersion();
        Food merged = (Food)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Food' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FoodIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Food' failed to initialize correctly", dod.getRandomFood());
        Food obj = dod.getNewTransientFood(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Food' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Food' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Food' identifier to no longer be null", obj.getId());
    }
    
}
