// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.etshost.msu.entity;

import com.etshost.msu.entity.FoodProperty;
import com.etshost.msu.entity.FoodPropertyDataOnDemand;
import com.etshost.msu.entity.FoodPropertyIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FoodPropertyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FoodPropertyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FoodPropertyIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FoodPropertyIntegrationTest: @Transactional;
    
    @Autowired
    FoodPropertyDataOnDemand FoodPropertyIntegrationTest.dod;
    
    @Test
    public void FoodPropertyIntegrationTest.testCountFoodPropertys() {
        Assert.assertNotNull("Data on demand for 'FoodProperty' failed to initialize correctly", dod.getRandomFoodProperty());
        long count = FoodProperty.countFoodPropertys();
        Assert.assertTrue("Counter for 'FoodProperty' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FoodPropertyIntegrationTest.testFindFoodProperty() {
        FoodProperty obj = dod.getRandomFoodProperty();
        Assert.assertNotNull("Data on demand for 'FoodProperty' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FoodProperty' failed to provide an identifier", id);
        obj = FoodProperty.findFoodProperty(id);
        Assert.assertNotNull("Find method for 'FoodProperty' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FoodProperty' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FoodPropertyIntegrationTest.testFindAllFoodPropertys() {
        Assert.assertNotNull("Data on demand for 'FoodProperty' failed to initialize correctly", dod.getRandomFoodProperty());
        long count = FoodProperty.countFoodPropertys();
        Assert.assertTrue("Too expensive to perform a find all test for 'FoodProperty', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FoodProperty> result = FoodProperty.findAllFoodPropertys();
        Assert.assertNotNull("Find all method for 'FoodProperty' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FoodProperty' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FoodPropertyIntegrationTest.testFindFoodPropertyEntries() {
        Assert.assertNotNull("Data on demand for 'FoodProperty' failed to initialize correctly", dod.getRandomFoodProperty());
        long count = FoodProperty.countFoodPropertys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FoodProperty> result = FoodProperty.findFoodPropertyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'FoodProperty' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FoodProperty' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FoodPropertyIntegrationTest.testFlush() {
        FoodProperty obj = dod.getRandomFoodProperty();
        Assert.assertNotNull("Data on demand for 'FoodProperty' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FoodProperty' failed to provide an identifier", id);
        obj = FoodProperty.findFoodProperty(id);
        Assert.assertNotNull("Find method for 'FoodProperty' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFoodProperty(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'FoodProperty' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FoodPropertyIntegrationTest.testMergeUpdate() {
        FoodProperty obj = dod.getRandomFoodProperty();
        Assert.assertNotNull("Data on demand for 'FoodProperty' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FoodProperty' failed to provide an identifier", id);
        obj = FoodProperty.findFoodProperty(id);
        boolean modified =  dod.modifyFoodProperty(obj);
        Integer currentVersion = obj.getVersion();
        FoodProperty merged = (FoodProperty)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'FoodProperty' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FoodPropertyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'FoodProperty' failed to initialize correctly", dod.getRandomFoodProperty());
        FoodProperty obj = dod.getNewTransientFoodProperty(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FoodProperty' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FoodProperty' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'FoodProperty' identifier to no longer be null", obj.getId());
    }
    
}
