// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.etshost.msu.entity;

import com.etshost.msu.entity.FoodDataOnDemand;
import com.etshost.msu.entity.FoodProperty;
import com.etshost.msu.entity.FoodProperty.PropertyType;
import com.etshost.msu.entity.FoodPropertyDataOnDemand;
import com.etshost.msu.entity.Status;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FoodPropertyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FoodPropertyDataOnDemand: @Component;
    
    private Random FoodPropertyDataOnDemand.rnd = new SecureRandom();
    
    private List<FoodProperty> FoodPropertyDataOnDemand.data;
    
    @Autowired
    FoodDataOnDemand FoodPropertyDataOnDemand.foodDataOnDemand;
    
    public FoodProperty FoodPropertyDataOnDemand.getNewTransientFoodProperty(int index) {
        FoodProperty obj = new FoodProperty();
        setCreated(obj, index);
        setModified(obj, index);
        setPropertyType(obj, index);
        setStatus(obj, index);
        setValue(obj, index);
        return obj;
    }
    
    public void FoodPropertyDataOnDemand.setCreated(FoodProperty obj, int index) {
        Instant created = null;
        obj.setCreated(created);
    }
    
    public void FoodPropertyDataOnDemand.setModified(FoodProperty obj, int index) {
        Instant modified = null;
        obj.setModified(modified);
    }
    
    public void FoodPropertyDataOnDemand.setPropertyType(FoodProperty obj, int index) {
        PropertyType propertyType = PropertyType.class.getEnumConstants()[0];
        obj.setPropertyType(propertyType);
    }
    
    public void FoodPropertyDataOnDemand.setStatus(FoodProperty obj, int index) {
        Status status = Status.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    public void FoodPropertyDataOnDemand.setValue(FoodProperty obj, int index) {
        double value = new Integer(index).doubleValue();
        obj.setValue(value);
    }
    
    public FoodProperty FoodPropertyDataOnDemand.getSpecificFoodProperty(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        FoodProperty obj = data.get(index);
        Long id = obj.getId();
        return FoodProperty.findFoodProperty(id);
    }
    
    public FoodProperty FoodPropertyDataOnDemand.getRandomFoodProperty() {
        init();
        FoodProperty obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return FoodProperty.findFoodProperty(id);
    }
    
    public boolean FoodPropertyDataOnDemand.modifyFoodProperty(FoodProperty obj) {
        return false;
    }
    
    public void FoodPropertyDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = FoodProperty.findFoodPropertyEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'FoodProperty' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<FoodProperty>();
        for (int i = 0; i < 10; i++) {
            FoodProperty obj = getNewTransientFoodProperty(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
