// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.etshost.msu.entity;

import com.etshost.msu.entity.Market;
import com.etshost.msu.entity.MarketDataOnDemand;
import com.etshost.msu.entity.Status;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect MarketDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MarketDataOnDemand: @Component;
    
    private Random MarketDataOnDemand.rnd = new SecureRandom();
    
    private List<Market> MarketDataOnDemand.data;
    
    public Market MarketDataOnDemand.getNewTransientMarket(int index) {
        Market obj = new Market();
        setAddress(obj, index);
        setCreated(obj, index);
        setEmail(obj, index);
        setHours(obj, index);
        setImage(obj, index);
        setLat(obj, index);
        setLng(obj, index);
        setModified(obj, index);
        setName(obj, index);
        setPhone(obj, index);
        setStatus(obj, index);
        setUrl(obj, index);
        return obj;
    }
    
    public void MarketDataOnDemand.setAddress(Market obj, int index) {
        String address = "address_" + index;
        obj.setAddress(address);
    }
    
    public void MarketDataOnDemand.setCreated(Market obj, int index) {
        Instant created = null;
        obj.setCreated(created);
    }
    
    public void MarketDataOnDemand.setEmail(Market obj, int index) {
        String email = "foo" + index + "@bar.com";
        obj.setEmail(email);
    }
    
    public void MarketDataOnDemand.setHours(Market obj, int index) {
        String hours = "hours_" + index;
        obj.setHours(hours);
    }
    
    public void MarketDataOnDemand.setImage(Market obj, int index) {
        byte[] image = String.valueOf(index).getBytes();
        obj.setImage(image);
    }
    
    public void MarketDataOnDemand.setLat(Market obj, int index) {
        Double lat = new Integer(index).doubleValue();
        obj.setLat(lat);
    }
    
    public void MarketDataOnDemand.setLng(Market obj, int index) {
        Double lng = new Integer(index).doubleValue();
        obj.setLng(lng);
    }
    
    public void MarketDataOnDemand.setModified(Market obj, int index) {
        Instant modified = null;
        obj.setModified(modified);
    }
    
    public void MarketDataOnDemand.setName(Market obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void MarketDataOnDemand.setPhone(Market obj, int index) {
        String phone = "phone_" + index;
        obj.setPhone(phone);
    }
    
    public void MarketDataOnDemand.setStatus(Market obj, int index) {
        Status status = Status.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    public void MarketDataOnDemand.setUrl(Market obj, int index) {
        String url = "url_" + index;
        obj.setUrl(url);
    }
    
    public Market MarketDataOnDemand.getSpecificMarket(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Market obj = data.get(index);
        Long id = obj.getId();
        return Market.findMarket(id);
    }
    
    public Market MarketDataOnDemand.getRandomMarket() {
        init();
        Market obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Market.findMarket(id);
    }
    
    public boolean MarketDataOnDemand.modifyMarket(Market obj) {
        return false;
    }
    
    public void MarketDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Market.findMarketEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Market' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Market>();
        for (int i = 0; i < 10; i++) {
            Market obj = getNewTransientMarket(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
