// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.etshost.msu.entity;

import com.etshost.msu.entity.Recipe;
import com.etshost.msu.entity.RecipeDataOnDemand;
import com.etshost.msu.entity.Status;
import com.etshost.msu.entity.UserDataOnDemand;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect RecipeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RecipeDataOnDemand: @Component;
    
    private Random RecipeDataOnDemand.rnd = new SecureRandom();
    
    private List<Recipe> RecipeDataOnDemand.data;
    
    @Autowired
    UserDataOnDemand RecipeDataOnDemand.userDataOnDemand;
    
    public Recipe RecipeDataOnDemand.getNewTransientRecipe(int index) {
        Recipe obj = new Recipe();
        setCreated(obj, index);
        setModified(obj, index);
        setServings(obj, index);
        setStatus(obj, index);
        return obj;
    }
    
    public void RecipeDataOnDemand.setCreated(Recipe obj, int index) {
        Instant created = null;
        obj.setCreated(created);
    }
    
    public void RecipeDataOnDemand.setModified(Recipe obj, int index) {
        Instant modified = null;
        obj.setModified(modified);
    }
    
    public void RecipeDataOnDemand.setServings(Recipe obj, int index) {
        int servings = index;
        obj.setServings(servings);
    }
    
    public void RecipeDataOnDemand.setStatus(Recipe obj, int index) {
        Status status = Status.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    public Recipe RecipeDataOnDemand.getSpecificRecipe(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Recipe obj = data.get(index);
        Long id = obj.getId();
        return Recipe.findRecipe(id);
    }
    
    public Recipe RecipeDataOnDemand.getRandomRecipe() {
        init();
        Recipe obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Recipe.findRecipe(id);
    }
    
    public boolean RecipeDataOnDemand.modifyRecipe(Recipe obj) {
        return false;
    }
    
    public void RecipeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Recipe.findRecipeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Recipe' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Recipe>();
        for (int i = 0; i < 10; i++) {
            Recipe obj = getNewTransientRecipe(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
