// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.etshost.msu.entity;

import com.etshost.msu.entity.ReviewDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ReviewDataOnDemand_Roo_Configurable {
    
    declare @type: ReviewDataOnDemand: @Configurable;
    
}
