// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.etshost.msu.entity;

import com.etshost.msu.entity.Entity;
import com.etshost.msu.entity.Review;
import com.etshost.msu.entity.ReviewDataOnDemand;
import com.etshost.msu.entity.Status;
import com.etshost.msu.entity.UserDataOnDemand;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ReviewDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ReviewDataOnDemand: @Component;
    
    private Random ReviewDataOnDemand.rnd = new SecureRandom();
    
    private List<Review> ReviewDataOnDemand.data;
    
    @Autowired
    UserDataOnDemand ReviewDataOnDemand.userDataOnDemand;
    
    public Review ReviewDataOnDemand.getNewTransientReview(int index) {
        Review obj = new Review();
        setCreated(obj, index);
        setModified(obj, index);
        setStatus(obj, index);
        setTarget(obj, index);
        setText(obj, index);
        return obj;
    }
    
    public void ReviewDataOnDemand.setCreated(Review obj, int index) {
        Instant created = null;
        obj.setCreated(created);
    }
    
    public void ReviewDataOnDemand.setModified(Review obj, int index) {
        Instant modified = null;
        obj.setModified(modified);
    }
    
    public void ReviewDataOnDemand.setStatus(Review obj, int index) {
        Status status = Status.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    public void ReviewDataOnDemand.setTarget(Review obj, int index) {
        Entity target = null;
        obj.setTarget(target);
    }
    
    public void ReviewDataOnDemand.setText(Review obj, int index) {
        String text = "text_" + index;
        obj.setText(text);
    }
    
    public Review ReviewDataOnDemand.getSpecificReview(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Review obj = data.get(index);
        Long id = obj.getId();
        return Review.findReview(id);
    }
    
    public Review ReviewDataOnDemand.getRandomReview() {
        init();
        Review obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Review.findReview(id);
    }
    
    public boolean ReviewDataOnDemand.modifyReview(Review obj) {
        return false;
    }
    
    public void ReviewDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Review.findReviewEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Review' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Review>();
        for (int i = 0; i < 10; i++) {
            Review obj = getNewTransientReview(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
