// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.etshost.msu.entity;

import com.etshost.msu.entity.NotificationFrequency;
import com.etshost.msu.entity.Status;
import com.etshost.msu.entity.User;
import com.etshost.msu.entity.UserDataOnDemand;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect UserDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserDataOnDemand: @Component;
    
    private Random UserDataOnDemand.rnd = new SecureRandom();
    
    private List<User> UserDataOnDemand.data;
    
    public User UserDataOnDemand.getNewTransientUser(int index) {
        User obj = new User();
        setAvatar(obj, index);
        setBackground(obj, index);
        setCreated(obj, index);
        setEmail(obj, index);
        setFirstName(obj, index);
        setGisOn(obj, index);
        setIrbAccept(obj, index);
        setLastName(obj, index);
        setModified(obj, index);
        setNotificationFrequency(obj, index);
        setPassword(obj, index);
        setPhone(obj, index);
        setStatus(obj, index);
        setTermsAccept(obj, index);
        setUsername(obj, index);
        return obj;
    }
    
    public void UserDataOnDemand.setAvatar(User obj, int index) {
        byte[] avatar = String.valueOf(index).getBytes();
        obj.setAvatar(avatar);
    }
    
    public void UserDataOnDemand.setBackground(User obj, int index) {
        byte[] background = String.valueOf(index).getBytes();
        obj.setBackground(background);
    }
    
    public void UserDataOnDemand.setCreated(User obj, int index) {
        Instant created = null;
        obj.setCreated(created);
    }
    
    public void UserDataOnDemand.setEmail(User obj, int index) {
        String email = "foo" + index + "@bar.com";
        obj.setEmail(email);
    }
    
    public void UserDataOnDemand.setFirstName(User obj, int index) {
        String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    public void UserDataOnDemand.setGisOn(User obj, int index) {
        Boolean gisOn = true;
        obj.setGisOn(gisOn);
    }
    
    public void UserDataOnDemand.setIrbAccept(User obj, int index) {
        Instant irbAccept = null;
        obj.setIrbAccept(irbAccept);
    }
    
    public void UserDataOnDemand.setLastName(User obj, int index) {
        String lastName = "lastName_" + index;
        obj.setLastName(lastName);
    }
    
    public void UserDataOnDemand.setModified(User obj, int index) {
        Instant modified = null;
        obj.setModified(modified);
    }
    
    public void UserDataOnDemand.setNotificationFrequency(User obj, int index) {
        NotificationFrequency notificationFrequency = null;
        obj.setNotificationFrequency(notificationFrequency);
    }
    
    public void UserDataOnDemand.setPassword(User obj, int index) {
        String password = "password_" + index;
        obj.setPassword(password);
    }
    
    public void UserDataOnDemand.setPhone(User obj, int index) {
        String phone = "phone_" + index;
        obj.setPhone(phone);
    }
    
    public void UserDataOnDemand.setStatus(User obj, int index) {
        Status status = Status.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    public void UserDataOnDemand.setTermsAccept(User obj, int index) {
        Instant termsAccept = null;
        obj.setTermsAccept(termsAccept);
    }
    
    public void UserDataOnDemand.setUsername(User obj, int index) {
        String username = "username_" + index;
        obj.setUsername(username);
    }
    
    public User UserDataOnDemand.getSpecificUser(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        User obj = data.get(index);
        Long id = obj.getId();
        return User.findUser(id);
    }
    
    public User UserDataOnDemand.getRandomUser() {
        init();
        User obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return User.findUser(id);
    }
    
    public boolean UserDataOnDemand.modifyUser(User obj) {
        return false;
    }
    
    public void UserDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = User.findUserEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'User' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<User>();
        for (int i = 0; i < 10; i++) {
            User obj = getNewTransientUser(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
