// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.etshost.msu.entity;

import com.etshost.msu.entity.Entity;
import java.util.List;
import javax.persistence.EntityManager;

privileged aspect Entity_Roo_Jpa_ActiveRecord {
    
    
}
