// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.etshost.msu.entity;

import com.etshost.msu.entity.Policy;

privileged aspect Policy_Roo_Jpa_Entity {
    
    public Policy.new() {
        super();
    }

}
