// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.etshost.msu.entity;

import com.etshost.msu.entity.UGC;
import com.etshost.msu.entity.User;

privileged aspect UGC_Roo_JavaBean {
    
    public User UGC.getUsr() {
        return this.usr;
    }
    
    public void UGC.setUsr(User usr) {
        this.usr = usr;
    }
    
}
