// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.etshost.msu.entity;

import com.etshost.msu.entity.Entity;
import com.etshost.msu.entity.User;
import com.etshost.msu.entity.Viewing;
import com.etshost.msu.entity.ViewingPk;
import java.time.Instant;

privileged aspect Viewing_Roo_JavaBean {
    
    
}
