name: ci

on:
  push:
    branches:
    - dev

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            dantheman2865/flint-eats-server:dev
            dantheman2865/flint-eats-server:${{ github.sha }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_HOST }}
          username: github-actions
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo IMAGE_VER=${{ github.sha }} > dev/ver
            docker compose -f dev-docker-compose.yml --env-file=dev/ver up -d